/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/57083098-f280-48ea-81ca-3012d9a624b8 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float water;
  bool addWater;
  bool systemState;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

  

#include "thingProperties.h"

const int trigPin = 5;
const int echoPin = 18;
const int relayPin = 19; 

long duration;
float distanceCm;

#define SOUND_SPEED 0.034
#define CM_TO_INCH 0.393701


void setup() {
  Serial.begin(115200);
  pinMode(trigPin, OUTPUT); 
  pinMode(echoPin, INPUT); 
  pinMode(relayPin, OUTPUT); 
  digitalWrite(relayPin, LOW); 
  
  delay(1500); 

  initProperties();

  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
 
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
}

void loop() {
  ArduinoCloud.update();
  digitalWrite(trigPin, LOW);
  delayMicroseconds(2);
  digitalWrite(trigPin, HIGH);
  delayMicroseconds(10);
  digitalWrite(trigPin, LOW);
  
  duration = pulseIn(echoPin, HIGH);
  distanceCm = duration * SOUND_SPEED / 2;

  int ceil = 10;
  int base =  0;

  float percentage = (ceil - distanceCm) * 10;
  if(percentage < 0) percentage = 0;
  water = percentage;


  if(distanceCm > 7)
  {
    digitalWrite(relayPin, HIGH);
    delay(1000)
    digitalWrite(relayPin, LOW);
    
  } 
  else
  {
    digitalWrite(relayPin, LOW); 
  }
      
  systemState = true;
  delay(1000);
  


}

void onWaterChange(){}

void onAddWaterChange() {
  if (addWater) {
    Serial.println("Adding water...");
  } else {
    Serial.println("Stopped adding water.");
  }
}

void onSystemStateChange() {
  if (systemState) {
    Serial.println("System is ON");
  } else {
    Serial.println("System is OFF");
  }
}